disabled_rules:
- trailing_whitespace
excluded:
- .build
- Build
- fastlane
- vendor
- Gemfile.locked
- Gemfile
- Pods

identifier_name:
 min_length: # only min_length
  error: 3 # only error
 max_length:
  warning: 50
 excluded: # excluded via string array
  - id

type_name:
 max_length: 50

type_body_length:
  - 300 # warning
  - 400 # error
